### PR TITLE
fix(client):bug:: Fix button once handler from not working after an error occurs

### LINKED ISSUE #147: Fix once pipe in lobby when Catniss mistakenly gets an error when joining or starting a game.
When Catniss gets an error after pressing **Start Game** or **Join Lobby**, she should be able to re-press the button once the error is solved to continue with the game.

Recreating error: 

1. Create a lobby
2. Open a second browser for a second player

- In the join lobby page:

3. Enter your display name as you would normally
4. Enter an incorrect lobby code, resulting in an error (as expected)
5. Enter the correct lobby code

### PR DESCRIPTION
**Pull request by SBAsai**
This PR will fix the original `button | once` handler from disabling in the event an error occurs. The buttons will now continue to work after an error has appeared while also only calling the attached function once.

### CODE REVIEW

**Review by zaverbac — DISMISSED** [review]

**Comment by SBAsai** [comment]
Forgot to add the fix to the splash page buttons too

**Review by zaverbac — DISMISSED** [review]

File: client/src/routes/+page.svelte [hunk 1]
```diff
@@ -17,6 +17,10 @@
 
   let errorMessage: string = "";
 
+  // variable that will be set true if the corresponding function has no errors thrown
+  // this will then allow the button to be pressed again if there is an error thrown
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: thia comment should use `/** */` because it describes the meaning of a variable

File: client/src/routes/+page.svelte [hunk 2]
```diff
@@ -17,6 +17,10 @@
...
+  let once: boolean = false;
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: I think we could find a more descriptive variable name maybe `buttonActive` or `waiting` or something like that

File: client/src/routes/+page.svelte [hunk 3]
```diff
@@ -91,8 +99,22 @@
...
       </Textfield>
-      <Button on:click|once={createLobbyHandler} disabled={!nameValidation.valid}><Label>Create Lobby</Label></Button>
-      <Button on:click|once={joinLobbyHandler} disabled={!nameValidation.valid}><Label>Join Lobby</Label></Button>
+      <Button
+        on:click={async () => {
+          if (once == false) {
+            await createLobbyHandler();
+          }
+        }}
+        disabled={!nameValidation.valid}><Label>Create Lobby</Label></Button
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: this if should be moved into the disabled

File: client/src/routes/+page.svelte [hunk 4]
```diff
@@ -91,8 +99,22 @@
...
+      >
+      <Button
+        on:click={async () => {
+          if (once == false) {
+            await joinLobbyHandler();
+          }
+        }}
+        disabled={!nameValidation.valid}><Label>Join Lobby</Label></Button
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: this if should be moved into the disabled

File: client/src/routes/join/+page.svelte [hunk 5]
```diff
@@ -104,7 +110,13 @@
   {#if errorMessage !== ""}
     <p class="error">{errorMessage}</p>
   {/if}
-  <form on:submit|once={joinLobby} on:submit|preventDefault>
+  <form
+    on:submit|preventDefault={async () => {
+      if (once == false) {
+        await joinLobby();
+      }
+    }}
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: this if should be moved into the disabled if that works for enter

File: client/src/routes/join/+page.svelte [hunk 6]
```diff
@@ -24,6 +24,8 @@
   let codeDirty: boolean = false;
   $: codeValidation = lobbyCodeValidator(code);
 
+  let once: boolean = false;
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: I think we could find a more descriptive variable name maybe `buttonActive` or `waiting` or something like that

File: client/src/components/Lobby.svelte [hunk 7]
```diff
@@ -15,6 +15,10 @@
   export let lobby: Lobby;
   let errorMessage: string = "";
 
+  // variable that will be set true if the corresponding function has no errors thrown
+  // this will then allow the button to be pressed again if there is an error thrown
+  let once: boolean = false;
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: I think we could find a more descriptive variable name maybe `startingGame` or `waiting` or something like that

File: client/src/components/Lobby.svelte [hunk 8]
```diff
@@ -15,6 +15,10 @@
   export let lobby: Lobby;
   let errorMessage: string = "";
 
+  // variable that will be set true if the corresponding function has no errors thrown
+  // this will then allow the button to be pressed again if there is an error thrown
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: thia comment should use `/** */` because it describes the meaning of a variable

File: client/src/components/Lobby.svelte [hunk 9]
```diff
@@ -77,14 +85,22 @@
...
   {#if auth.currentUser?.uid === lobby.uids[0]}
     <div class="actions">
-      <Button on:click|once={() => start()}><Label>Start Game</Label></Button>
+      <Button
+        on:click={async () => {
+          if (once == false) {
+            await start();
+          }
+        }}><Label>Start Game</Label></Button
+      >
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: this if should be moved into the disabled

File: client/src/components/Lobby.svelte [hunk 10]
```diff
@@ -77,14 +85,22 @@
...
   <div class="actions">
     <Button
-      on:click|once={async () => {
+      on:click={async () => {
+        if(once == false) {
         await leave();
         goto("/");
+        }
       }}><Label>Leave Lobby</Label></Button
     >
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: this if should be moved into the disabled

**Review by nstringham — DISMISSED** [review]

File: client/src/routes/join/+page.svelte (hunk 5 above)
Comment (SBAsai) [reply client/src/routes/join/+page.svelte]: Seems like it works

File: client/src/routes/+page.svelte (hunk 2 above)
Comment (SBAsai) [reply client/src/routes/+page.svelte]: I'll just name all of them `waiting`

**Review by gchamb — DISMISSED** [review]
Looks good to me. The user could hypothetically remove the disabled property and then spam but idk if there's a way to check serverside to rate limit their requests

**Comment by nstringham** [comment]
> Looks good to me. The user could hypothetically remove the disabled property and then spam but idk if there's a way to check serverside to rate limit their requests

I feel like server side rate limiting is outside the scope of this card

**Comment by gchamb** [comment]
> I feel like server side rate limiting is outside the scope of this card

I would agree just throwing the idea out there

File: client/src/components/Lobby.svelte [hunk 11]
```diff
@@ -74,15 +84,21 @@
   <SelectAvatar {lobby} on:change={(event) => onAvatarSelect(event.detail.value)} />
   {#if auth.currentUser?.uid === lobby.uids[0]}
     <div class="actions">
-      <Button on:click|once={() => start()}><Label>Start Game</Label></Button>
+      <Button
+        on:click={async () => {
+          await start();
+        }}
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: this can be `() => start()` like it was before this PR

File: client/src/components/Lobby.svelte [hunk 12]
```diff
@@ -15,6 +15,12 @@
   export let lobby: Lobby;
   let errorMessage: string = "";
 
+  /**
+  variable that will be set true if the corresponding function has no errors thrown
+  this will then allow the button to be pressed again if there is an error thrown
+  */
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: each line should start with a `* `

 ```ts
  /**
   * variable that will be set true if the corresponding function has no errors thrown
   * this will then allow the button to be pressed again if there is an error thrown
   */
 ```

File: client/src/routes/+page.svelte [hunk 13]
```diff
@@ -91,8 +101,18 @@
       >
         <HelperText validationMsg slot="helper">{nameValidation.valid ? "" : nameValidation.reason}</HelperText>
       </Textfield>
-      <Button on:click|once={createLobbyHandler} disabled={!nameValidation.valid}><Label>Create Lobby</Label></Button>
-      <Button on:click|once={joinLobbyHandler} disabled={!nameValidation.valid}><Label>Join Lobby</Label></Button>
+      <Button
+        on:click={async () => {
+          await createLobbyHandler();
+        }}
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: this can just be `on:click={createLobbyHandler}` like it was before

File: client/src/routes/+page.svelte [hunk 14]
```diff
@@ -91,8 +101,18 @@
...
+        disabled={!nameValidation.valid || waiting}><Label>Create Lobby</Label></Button
+      >
+      <Button
+        on:click={async () => {
+          await joinLobbyHandler();
+        }}
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: this can just be `on:click={joinLobbyHandler}` like it was before

File: client/src/routes/+page.svelte [hunk 15]
```diff
@@ -17,6 +17,12 @@
 
   let errorMessage: string = "";
 
+  /**
+  variable that will be set true if the corresponding function has no errors thrown
+  this will then allow the button to be pressed again if there is an error thrown
+  */
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: see other comment about doc comment formating

File: client/src/routes/join/+page.svelte [hunk 16]
```diff
@@ -24,6 +24,12 @@
   let codeDirty: boolean = false;
   $: codeValidation = lobbyCodeValidator(code);
 
+  /**
+  variable that will be set true if the corresponding function has no errors thrown
+  this will then allow the button to be pressed again if there is an error thrown
+  */
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: see other comment about doc comment formating

File: client/src/routes/join/+page.svelte [hunk 17]
```diff
@@ -54,18 +60,22 @@
...
       // enter lobby with the user's info
       await findAndJoinLobby(code);
       // go to game page
       goto(`/game?code=${code}`);
     } catch (err) {
+      waiting = false;
       // if the lobby doesn't exist then error is thrown
       errorMessage = err instanceof Error ? err.message : String(err);
       if (errorMessage == "You are already in the lobby!") {
+        waiting = true;
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte:79]: what does this do?

File: client/src/routes/join/+page.svelte [hunk 18]
```diff
@@ -104,7 +114,14 @@
...
     <p class="error">{errorMessage}</p>
   {/if}
-  <form on:submit|once={joinLobby} on:submit|preventDefault>
+  <form
+    on:submit|preventDefault={async () => {
+      if (waiting == false) {
+        await joinLobby();
+      }
+    }}
+    disabled={waiting}
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: this should probobly be on the submit button instead of the form

File: client/src/routes/join/+page.svelte [hunk 19]
```diff
@@ -104,7 +114,14 @@
   {#if errorMessage !== ""}
     <p class="error">{errorMessage}</p>
   {/if}
-  <form on:submit|once={joinLobby} on:submit|preventDefault>
+  <form
+    on:submit|preventDefault={async () => {
+      if (waiting == false) {
+        await joinLobby();
+      }
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: Do you need this `if` if you alread have the disabled?

**Review by nstringham — DISMISSED** [review]

File: client/src/routes/join/+page.svelte (hunk 17 above)
Comment (SBAsai) [reply client/src/routes/join/+page.svelte:79]: If you are already in the lobby, the button should be disabled. Otherwise other errors being thrown should keep `waiting = false`

**Review by gchamb — DISMISSED** [review]

File: client/src/components/Lobby.svelte [hunk 20]
```diff
@@ -85,17 +95,18 @@
   <SelectAvatar {lobby} on:change={(event) => onAvatarSelect(event.detail.value)} />
   {#if $user?.uid === lobby.uids[0]}
     <div class="actions">
-      <Button on:click|once={() => start()} disabled={lobby.players.length < minPlayers}
+      <Button on:click|once={() => start()} disabled={lobby.players.length < minPlayers || waiting}
```
Comment (nstringham) [inline client/src/components/Lobby.svelte]: why is this still `once`

File: client/src/routes/+page.svelte [hunk 21]
```diff
@@ -91,8 +101,10 @@
       >
         <HelperText validationMsg slot="helper">{nameValidation.valid ? "" : nameValidation.reason}</HelperText>
       </Textfield>
-      <Button on:click|once={createLobbyHandler} disabled={!nameValidation.valid}><Label>Create Lobby</Label></Button>
-      <Button on:click|once={joinLobbyHandler} disabled={!nameValidation.valid}><Label>Join Lobby</Label></Button>
+      <Button on:click={createLobbyHandler} disabled={!nameValidation.valid || waiting}
+        ><Label>Create Lobby</Label></Button
+      >
```
Comment (nstringham) [inline client/src/routes/+page.svelte]: I would prefer if this was formatted like
```html
<Button on:click={createLobbyHandler} disabled={!nameValidation.valid || waiting}>
  <Label>Create Lobby</Label>
</Button>
```

File: client/src/routes/join/+page.svelte [hunk 22]
```diff
@@ -104,7 +115,11 @@
   {#if errorMessage !== ""}
     <p class="error">{errorMessage}</p>
   {/if}
-  <form on:submit|once={joinLobby} on:submit|preventDefault>
+  <form
+    on:submit|preventDefault={async () => {
+        await joinLobby();
+      }}
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: this can just be `joinLobby` instead of `async () => { await joinLobby(); }`

**Review by nstringham — DISMISSED** [review]
Seams good just a few tiny changes

**Review by gchamb — DISMISSED** [review]

File: client/src/routes/join/+page.svelte [hunk 23]
```diff
@@ -116,10 +116,8 @@
     <p class="error">{errorMessage}</p>
   {/if}
   <form
-    on:submit|preventDefault={async () => {
-        await joinLobby();
-      }}
-  >
+    on:submit|preventDefault={joinLobby}
```
Comment (nstringham) [inline client/src/routes/join/+page.svelte]: can this be all on one line

**Review by nstringham — DISMISSED** [review]

**Review by nstringham — APPROVED** [review]
