### PR TITLE
fix(client):🐛Fix lobby chat issue that doesn't let users leave lobby

### LINKED ISSUE #153: Fix leave lobby bug
Users aren't allowed to leave game. This is because of LobbyChat.svelte. The user does leave the lobby on the backend.

to recreate the error:
1. create a lobby
2. join the lobby with a new account and the new user shouldn't be able to leave the lobby.

### PR DESCRIPTION
**Pull request by Muaad2001**
Users can now leave the lobby.

### CODE REVIEW

File: client/src/routes/game/+page.svelte [hunk 1]
```diff
@@ -119,6 +124,7 @@
   {:else}
     unknown lobby state: {lobby.state}
   {/if}
+  <!-- put lobbychat were alive users will be able to access it -->
```
Comment (njumaah) [inline client/src/routes/game/+page.svelte]: what is this

**Review by njumaah — CHANGES_REQUESTED** [review]

**Review by njumaah — APPROVED** [review]
