### PR TITLE
fix(functions): 🐛 stalker prompt shows and no multiple stalkers

### LINKED ISSUE #161: Stalker's prompt answer gets deleted/does not save
For some reason, the stalker's prompt answer never shows during the voting phase. (my assumption would be that we are getting the prompt answers from the chat phase instead of the prompt phase)

In chat.ts it looks like prompt is being stored once the chat rooms are deleted.

### PR DESCRIPTION
**Pull request by gchamb**
This shows the stalker's prompt answer and fixes the multiple stalker/spectator problem.

ignore the branch name should just be gchamb/fix-stalker

### CODE REVIEW

**Review by mrjoshua520 — DISMISSED** [review]
Looks great! Someone else should look at it before merging though

**Review by nstringham — DISMISSED** [review]
we decided we should not delete prompt answers at the end pf prompt and use that at the beginning of vote and we should also delete chat messages asyncrounstly after setting the state t vote

File: functions/src/lobby.ts [hunk 1]
```diff
@@ -510,7 +523,13 @@ export const verifyExpiration = functions.https.onCall(async (data, context): Pr
       await determineWinner(lobbyDoc, transaction);
     }
   });
+
+  if (lobby?.state == "CHAT") {
+    await deleteChatCollections(lobbyDocRef);
+  }
+
   if (lobby?.state == "VOTE") {
+    await deletePromptAnswers(lobbyDocRef);
```
Comment (nstringham) [inline functions/src/lobby.ts]: why are prompt answers being deleted twice?

File: functions/src/chat.ts [hunk 2]
```diff
@@ -19,44 +20,50 @@ export async function deleteLobbyChatMessages(lobbyDoc: DocumentReference<Lobby>
...
-export async function deleteChatRooms(lobbyData: Lobby, lobbyDoc: DocumentReference<Lobby>, transaction: Transaction) {
+export async function deleteChatCollections(lobbyDoc: firestore.DocumentReference<Lobby>) {
+  const batch = db.batch();
+
+  const chatRooms = await getChatRoomCollection(lobbyDoc).get();
+
+  for (const chatRoomDoc of chatRooms.docs) {
+    // place messages in batch
+    const chatMessages = await getChatRoomMessagesCollection(chatRoomDoc.ref).get();
+    chatMessages.docs.map((messageDoc) => batch.delete(messageDoc.ref));
```
Comment (nstringham) [inline functions/src/chat.ts]: this does not return anything so it should be a map.

maybe conside a for of loop

File: functions/src/chat.ts [hunk 3]
```diff
@@ -19,44 +20,50 @@ export async function deleteLobbyChatMessages(lobbyDoc: DocumentReference<Lobby>
...
-    transaction.delete(room);
-  }
+  // iterate through promptAnswer docs and place the answer on their player object
+  for (const promptAnswerDoc of promptAnswersSnaphot.docs) {
+    const promptData = promptAnswerDoc.data();
+    let promptAns = promptData.answer;
 
-  for (const stalker of stalkers.docs) {
-    transaction.update(stalker.ref, { stalker: false });
+    if (promptAns === "" || !promptAnswerDoc.exists) {
```
Comment (nstringham) [inline functions/src/chat.ts]: don't need to check `!promptAnswerDoc.exists` because querries already garentee that the documents exist

File: functions/src/chat.ts [hunk 4]
```diff
@@ -19,44 +20,50 @@ export async function deleteLobbyChatMessages(lobbyDoc: DocumentReference<Lobby>
...
+      promptAns = "no answer";
+    }
+
+    const playerIndex = uids.indexOf(promptAnswerDoc.id);
+    players[playerIndex].promptAnswer = promptAns;
```
Comment (nstringham) [inline functions/src/chat.ts:63]: I feel like this could just be `players[playerIndex].promptAnswer = promptData.answer ?? "no answer"`

**Review by nstringham — DISMISSED** [review]
one disavantage of what we are doing here iswe read the prompt awnsers twice at the end of chat once in `setAnswers` and once in `deletePromptAnswers` we could store if and reuse it but I think this is probobly fine for now

**Review by nstringham — APPROVED** [review]

**Review by mrjoshua520 — APPROVED** [review]
